import importlib.util
import json
import sys
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve().parents[3] / "src" / "sirius_skills" / "commands" / "scaffold_design.py"
PLANNING_SCRIPT_PATH = (
    Path(__file__).resolve().parents[3] / "src" / "sirius_skills" / "commands" / "manage_planning.py"
)
SUBFEATURE_SCRIPT_PATH = (
    Path(__file__).resolve().parents[3] / "src" / "sirius_skills" / "commands" / "manage_subfeatures.py"
)


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def run_cli(module, script_name: str, monkeypatch, *args):
    monkeypatch.setattr(sys, "argv", [script_name, *args])
    return module.main()


def write_file(path: Path, content: str = "# doc\n"):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def setup_feature(tmp_path: Path):
    planning_module = load_module(PLANNING_SCRIPT_PATH, "design_manage_planning")
    feature_dir = tmp_path / "docs" / "features" / "checkout"
    feature_dir.mkdir(parents=True, exist_ok=True)
    (tmp_path / ".skills").mkdir(parents=True, exist_ok=True)
    (tmp_path / ".skills" / "planning.json").write_text(
        json.dumps({"planning_dir": "docs/features"}) + "\n", encoding="utf-8"
    )
    feature_dir_str, _ = planning_module.create_feature("checkout")
    feature_path = Path(feature_dir_str)
    write_file(feature_path / "discover.md", "# Discover\n")
    write_file(
        feature_path / "user-stories.md",
        "# Stories\n\n- **CHK-01 (M)**: Update checkout flow.\n",
    )
    planning_module.sync_registry()
    return feature_path


def setup_subfeature(tmp_path: Path, monkeypatch):
    subfeature_module = load_module(SUBFEATURE_SCRIPT_PATH, "design_manage_subfeatures")
    monkeypatch.chdir(tmp_path)
    feature_path = setup_feature(tmp_path)
    assert run_cli(
        subfeature_module,
        "manage_subfeatures.py",
        monkeypatch,
        "add",
        "checkout",
        "replace-legacy-flow",
        "--type",
        "narrowing",
        "--summary",
        "Retire the legacy checkout copy path",
    ) == 0
    subfeature_path = feature_path / "subfeatures" / "replace-legacy-flow"
    write_file(subfeature_path / "discover.md", "# Discover\n")
    write_file(subfeature_path / "impact-analysis.md", "# Impact\n")
    return subfeature_path


def test_scaffold_design_creates_feature_scaffold(tmp_path, monkeypatch):
    module = load_module(SCRIPT_PATH, "scaffold_design")
    monkeypatch.chdir(tmp_path)
    feature_path = setup_feature(tmp_path)

    assert run_cli(module, "scaffold_design.py", monkeypatch, "checkout") == 0

    content = (feature_path / "system-design.md").read_text(encoding="utf-8")
    assert "# System design: Checkout" in content
    assert "## Related stories" in content
    assert "## System design diagrams" in content
    assert "feature-level PlantUML diagram" in content
    assert "`CHK-01`" in content
    assert "Scaffold generated by `sirius scaffold-design`." in content


def test_scaffold_design_creates_subfeature_scaffold(tmp_path, monkeypatch):
    module = load_module(SCRIPT_PATH, "scaffold_design_subfeature")
    monkeypatch.chdir(tmp_path)
    subfeature_path = setup_subfeature(tmp_path, monkeypatch)

    assert run_cli(
        module,
        "scaffold_design.py",
        monkeypatch,
        "docs/features/checkout/subfeatures/replace-legacy-flow",
    ) == 0

    content = (subfeature_path / "system-design.md").read_text(encoding="utf-8")
    assert "# System design: Replace Legacy Flow" in content
    assert "- Parent feature: `checkout`" in content
    assert "- Impact analysis: `present`" in content
