#!/usr/bin/env python3

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_DIR = SCRIPT_DIR.parent
REPO_ROOT = SKILL_DIR.parents[1]
PLANNING_SCRIPT = REPO_ROOT / "skills" / "guide-planning" / "scripts" / "manage_planning.py"
SUBFEATURE_SCRIPT = REPO_ROOT / "skills" / "add-subfeature" / "scripts" / "manage_subfeatures.py"
SYSTEM_DESIGN_FILE = "system-design.md"
SUBFEATURE_METADATA_FILE = ".subfeature-meta.json"
BACKTICK_ID_PATTERN = re.compile(r"`([A-Za-z][A-Za-z0-9._-]+)`")
STORY_HEADER_PATTERN = re.compile(r"^\s*[-*]\s+`([A-Za-z][A-Za-z0-9._-]+)`", re.MULTILINE)
BOLD_STORY_PATTERN = re.compile(r"\*\*([A-Za-z][A-Za-z0-9._-]+)(?:\s+\([^)]*\))?\*\*")


def load_module(script_path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, script_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module from {script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold a system-design.md planning artifact for a feature or subfeature."
    )
    parser.add_argument("target", help="Feature selector or planning packet path.")
    parser.add_argument("--scope", default=None, help="Optional planning scope path.")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing system-design.md scaffold.",
    )
    return parser.parse_args()


def title_from_slug(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").strip().title()


def is_subfeature_target(target_dir: Path) -> bool:
    return (target_dir / SUBFEATURE_METADATA_FILE).is_file()


def relative_to_cwd(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(path)


def collect_story_ids(target_dir: Path, subfeature_metadata: dict[str, object] | None) -> list[str]:
    if subfeature_metadata is not None:
        story_ids = [
            str(item).strip()
            for item in subfeature_metadata.get("affected_story_ids", [])
            if isinstance(item, str) and item.strip()
        ]
        if story_ids:
            return list(dict.fromkeys(story_ids))

    user_stories = target_dir / "user-stories.md"
    if not user_stories.is_file():
        return []
    text = user_stories.read_text(encoding="utf-8")
    story_ids = STORY_HEADER_PATTERN.findall(text)
    if story_ids:
        return list(dict.fromkeys(story_ids))
    story_ids = BOLD_STORY_PATTERN.findall(text)
    if story_ids:
        return list(dict.fromkeys(story_ids))
    return list(dict.fromkeys(BACKTICK_ID_PATTERN.findall(text)))


def render_story_list(story_ids: list[str]) -> str:
    if not story_ids:
        return "- `TBD`: replace this placeholder with the stories the design directly serves."
    return "\n".join(f"- `{story_id}`" for story_id in story_ids)


def build_scaffold(
    *,
    target_slug: str,
    target_dir: Path,
    planning_status: str,
    subfeature_metadata: dict[str, object] | None,
) -> str:
    title = title_from_slug(target_slug)
    story_ids = collect_story_ids(target_dir, subfeature_metadata)
    discover_exists = (target_dir / "discover.md").is_file()
    impact_exists = (target_dir / "impact-analysis.md").is_file()
    research_exists = (target_dir / "reference-research.md").is_file()

    context_lines = [
        f"- Planning path: `{relative_to_cwd(target_dir)}`",
        f"- Current planning status: `{planning_status}`",
        f"- Discover input: `{'present' if discover_exists else 'missing'}`",
    ]
    if subfeature_metadata is not None:
        context_lines.append(
            f"- Parent feature: `{subfeature_metadata['parent_feature_slug']}`"
        )
        context_lines.append(
            f"- Subfeature type: `{subfeature_metadata['subfeature_type']}`"
        )
        context_lines.append(
            f"- Impact analysis: `{'present' if impact_exists else 'missing'}`"
        )
    if research_exists:
        context_lines.append("- Reference research: `present`")

    return f"""# System design: {title}

> Scaffold generated by `skills/design/scripts/scaffold_design.py`.
> Replace the placeholder guidance with the real design before advancing planning state.

## Design summary

- State the main architectural decision for this packet.
- Explain why this approach is preferable to the obvious alternatives.
- Keep the summary short enough that `breakdown` can reuse it as the design baseline.

## Related stories

{render_story_list(story_ids)}

## Goals and non-goals

### Goals

- Describe the concrete user-facing or system-facing outcomes this design must satisfy.

### Non-goals

- Record what this packet will deliberately not solve.

## Architecture

- Describe the major structural decision, ownership boundaries, and any diagrams that should be added.
- Call out whether the packet reuses an existing parent or sibling feature seam.

## Interfaces and dependencies

- List the local modules, commands, protocols, or planning artifacts this design depends on.
- Describe the input/output contracts that later slices must preserve.

## Configuration surfaces and ownership

- Name each control surface that owns externally supplied values.
- Record why no new env vars, CLI flags, or duplicate typed carriers are needed, or justify the delta if one is required.

## Data flow, state, and lifecycle

- Document the important state transitions, local modes, and lifecycle invariants.
- Include concurrency or shared-state rules when they affect correctness.

## Failure handling and operational constraints

- List the expected failure modes, fallback behavior, and terminal/runtime caveats.
- Explain how the shipped path degrades when dependencies or platform capabilities are absent.

## Alternatives considered

- Record the main rejected options and why they lost.

## Risks, assumptions, and open questions

- Capture the unresolved questions that should affect later slice ordering or review.

## Validation strategy

- Describe the tests, smoke checks, or manual validation needed before implementation is considered complete.

## Summary

- Restate the chosen design in one short paragraph.

## Input context

{chr(10).join(context_lines)}
"""


def main() -> int:
    args = parse_args()
    planning = load_module(PLANNING_SCRIPT, "scaffold_design_manage_planning")
    subfeatures = load_module(SUBFEATURE_SCRIPT, "scaffold_design_manage_subfeatures")

    try:
        rows, feature, scope_context = planning.resolve_feature_lookup(
            args.target, explicit_scope=args.scope
        )
        if feature is None:
            raise RuntimeError(f"Planning target not found: {args.target}")
        target_dir = Path(planning.feature_dir_for_row(feature, scope_context=scope_context))
        planning_metadata = planning.read_metadata(str(target_dir))
        subfeature_metadata = (
            subfeatures.read_metadata(str(target_dir)) if is_subfeature_target(target_dir) else None
        )
        design_path = target_dir / SYSTEM_DESIGN_FILE
        if design_path.exists() and not args.force:
            raise RuntimeError(
                f"System design already exists at '{relative_to_cwd(design_path)}'. Use --force to overwrite it."
            )
        target_slug = (
            str(subfeature_metadata["subfeature_id"])
            if subfeature_metadata is not None
            else str(feature["feature"])
        )
        design_path.write_text(
            build_scaffold(
                target_slug=target_slug,
                target_dir=target_dir,
                planning_status=str(planning_metadata["status"]),
                subfeature_metadata=subfeature_metadata,
            ),
            encoding="utf-8",
        )
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    print(f"Scaffolded system design: {relative_to_cwd(design_path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
